"""
Indo Marine Watch (IMW) — Maritime Intelligence Backend

Canonical FastAPI service for real SAR oil-spill analysis, AIS candidate
correlation, environmental drift evidence, and operator-reviewed drafts.

No synthetic SAR, AIS, RF, or Coast Guard transmission is generated by the
canonical API. Missing external evidence is returned explicitly.
"""

from __future__ import annotations

import json
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

BASE_DIR = Path(__file__).resolve().parent
MAIN_DIR = BASE_DIR / "main"
TEMP_DIR = BASE_DIR / "temp"
STATIC_DIR = BASE_DIR / "static"
TEMP_DIR.mkdir(exist_ok=True)

if str(MAIN_DIR) not in sys.path:
    sys.path.insert(0, str(MAIN_DIR))
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from main.drift_analysis import drift_to_dict, enrich_incident_with_drift, estimate_source_zone
from main.environmental_provider import OpenMeteoEnvironmentalProvider
from main.imw_real_pipeline import run_real_pipeline
from main.incident_report import build_incident_report
from main.ais_matcher import AIS_CSV_PATH
from main.predict_and_classify import CHECKPOINT_PATH as SLICK_CHECKPOINT_PATH
from main.ship_detection_module import WEIGHTS_PATH as HULL_CHECKPOINT_PATH

app = FastAPI(
    title="Indo Marine Watch (IMW)",
    description="Maritime intelligence for SAR oil-spill detection and vessel investigation",
    version="5.2.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


class AnalyzeTrafficRequest(BaseModel):
    slick_lat: float
    slick_lon: float
    hull_lat: float
    hull_lon: float
    capture_time: Optional[str] = None


class DriftAnalysisRequest(BaseModel):
    incident: Dict[str, Any]
    observations: List[Dict[str, Any]] = Field(default_factory=list)
    windage: float = Field(default=0.03, ge=0.0, le=0.2)
    uncertainty_km: float = Field(default=2.0, ge=0.1, le=100.0)


class PrepareResponseRequest(BaseModel):
    incident_id: str
    slick_centroid: List[float]
    spill_area_sq_m: float
    suspect_vessel: Dict[str, Any]
    threat_score: float
    evidence_summary: Optional[str] = None
    recipient: Optional[str] = None


class BuildReportRequest(BaseModel):
    incident: Dict[str, Any]
    response_draft: Optional[Dict[str, Any]] = None


def _parse_environmental_observations(raw: Optional[str]) -> List[Dict[str, Any]]:
    if not raw:
        return []
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=422,
            detail=f"environmental_observations_json must be valid JSON: {exc.msg}",
        ) from exc
    if not isinstance(value, list) or any(not isinstance(item, dict) for item in value):
        raise HTTPException(
            status_code=422,
            detail="environmental_observations_json must be a JSON list of objects",
        )
    return value


def _incident_spill_anchor(
    incident: Dict[str, Any],
) -> tuple[float | None, float | None, str | None]:
    spill = incident.get("spill") or {}
    components = spill.get("components") or []
    location = next((c.get("geolocation") for c in components if c.get("geolocation")), None)
    detection = incident.get("detection") or {}
    return (
        location.get("lat") if location else None,
        location.get("lon") if location else None,
        detection.get("timestamp"),
    )


def _attach_live_environment(result: Dict[str, Any]) -> Dict[str, Any]:
    incident = result.get("incident")
    if not isinstance(incident, dict):
        return result

    lat, lon, timestamp = _incident_spill_anchor(incident)
    if lat is None or lon is None or not timestamp:
        result["environmental"] = {
            "status": "NOT_AVAILABLE",
            "provider": "Open-Meteo Marine + Forecast API",
            "observation_count": 0,
            "reason": "A real georeferenced spill location and detection timestamp are required before environmental retrieval.",
        }
        return result

    try:
        detection_time = datetime.fromisoformat(str(timestamp).replace("Z", "+00:00"))
        rows = OpenMeteoEnvironmentalProvider().get_observations(lat, lon, detection_time, window_hours=3)
        enriched = enrich_incident_with_drift(incident, rows)
        result["incident"] = enriched
        result["drift"] = enriched.get("drift")
        result["environmental"] = {
            **(enriched.get("environmental") or {}),
            "provider": "Open-Meteo Marine + Forecast API",
            "source_status": "REAL_MODELLED_DATA",
            "observation_count": len(rows),
        }
    except Exception as exc:
        unavailable_drift = estimate_source_zone(lat, lon, timestamp, [])
        result["drift"] = drift_to_dict(unavailable_drift)
        result["environmental"] = {
            "status": "UNAVAILABLE",
            "provider": "Open-Meteo Marine + Forecast API",
            "source_status": "PROVIDER_ERROR",
            "observation_count": 0,
            "reason": f"Environmental provider unavailable: {type(exc).__name__}: {exc}",
        }
        result["incident"]["drift"] = result["drift"]
        result["incident"]["environmental"] = result["environmental"]
    return result


@app.get("/api/health")
async def health() -> Dict[str, Any]:
    """Read-only deployment diagnostics; never runs model inference."""
    return {
        "status": "ok",
        "service": "Indo Marine Watch",
        "version": app.version,
        "data_integrity": "REAL_ONLY",
        "dependencies": {
            "slick_checkpoint": {
                "path": SLICK_CHECKPOINT_PATH,
                "available": Path(SLICK_CHECKPOINT_PATH).exists(),
            },
            "hull_checkpoint": {
                "path": HULL_CHECKPOINT_PATH,
                "available": Path(HULL_CHECKPOINT_PATH).exists(),
            },
            "ais_source": {
                "path": AIS_CSV_PATH,
                "available": Path(AIS_CSV_PATH).exists(),
                "status": "CONFIGURED_REAL_SOURCE" if Path(AIS_CSV_PATH).exists() else "UNAVAILABLE",
            },
            "environment_provider": "Open-Meteo Marine + Forecast API",
            "rf": "NOT_IMPLEMENTED",
        },
    }


@app.post("/api/process-sar")
async def process_sar(
    file: UploadFile = File(...),
    center_lat: Optional[float] = Form(None),
    center_lon: Optional[float] = Form(None),
    environmental_observations_json: Optional[str] = Form(None),
    use_live_environment: bool = Form(True),
):
    t_start = time.perf_counter()
    safe_name = Path(file.filename or "upload.png").name
    file_path = TEMP_DIR / f"{uuid.uuid4().hex[:8]}_{safe_name}"
    file_path.write_bytes(await file.read())
    observations = _parse_environmental_observations(environmental_observations_json)

    try:
        result = run_real_pipeline(
            file_path,
            center_lat=center_lat,
            center_lon=center_lon,
            use_ais=True,
            environmental_observations=observations,
        )
        if not observations and use_live_environment:
            result = _attach_live_environment(result)

        incident_id = result.get("incident", {}).get("incident_id") or f"IMW-{uuid.uuid4().hex[:8].upper()}-2026"
        result["incident_id"] = incident_id
        if isinstance(result.get("incident"), dict):
            result["incident"]["incident_id"] = incident_id
        result["pipeline_latency_ms"] = round((time.perf_counter() - t_start) * 1000, 2)
        return {"status": "success", **result}
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=503, detail=f"IMW real pipeline unavailable: {exc}") from exc
    finally:
        try:
            file_path.unlink(missing_ok=True)
        except OSError:
            pass


@app.post("/api/analyze-traffic")
async def analyze_traffic(request: AnalyzeTrafficRequest) -> Dict[str, Any]:
    """Correlate a detected SAR hull against configured real AIS data."""
    from main.ais_matcher import assess_ais_coverage, load_ais_data, match_hull_to_ais

    ais_path = Path(AIS_CSV_PATH)
    if not ais_path.exists():
        return {
            "status": "success",
            "data_integrity": "REAL_ONLY",
            "ais_status": "NO_AIS_COVERAGE",
            "ais_gap_observed": False,
            "is_dark_vessel": False,
            "rf_intercept": {"status": "NOT_IMPLEMENTED"},
            "ais_track": [],
            "surrounding_traffic": [],
            "attribution_reason": "Configured AIS source is unavailable; no vessel attribution is made.",
        }

    ais_df = load_ais_data(str(ais_path))
    capture_time = (
        datetime.fromisoformat(request.capture_time.replace("Z", "+00:00")).replace(tzinfo=None)
        if request.capture_time
        else datetime.now(timezone.utc).replace(tzinfo=None)
    )
    coverage = assess_ais_coverage(ais_df, request.hull_lat, request.hull_lon, capture_time)
    match = match_hull_to_ais(request.hull_lat, request.hull_lon, capture_time, ais_df, hull_id=0)
    status = "AIS_MATCHED" if match.has_ais_match else coverage.status
    return {
        "status": "success",
        "data_integrity": "REAL_ONLY",
        "ais_status": status,
        "ais_gap_observed": False,
        "is_dark_vessel": False,
        "suspect_vessel": {
            "name": match.matched_vessel_name or "UNIDENTIFIED",
            "mmsi": match.matched_mmsi or "---",
            "flag": "UNKNOWN",
            "type": "AIS-correlated vessel" if match.has_ais_match else "Unresolved SAR hull",
            "coordinates": [request.hull_lat, request.hull_lon],
            "threat_score": match.suspicion_score,
        },
        "rf_intercept": {"status": "NOT_IMPLEMENTED", "match": False, "signature": None, "lock_coordinates": None},
        "ais_track": [],
        "ais_blackout_point": None,
        "surrounding_traffic": [],
        "attribution_reason": coverage.reason if not match.has_ais_match else match.reason,
        "ais_match": {
            "matched_mmsi": match.matched_mmsi,
            "matched_vessel_name": match.matched_vessel_name,
            "distance_km": match.distance_km,
            "time_diff_hours": match.time_diff_hours,
            "suspicion_score": match.suspicion_score,
        },
        "coverage": {
            "status": coverage.status,
            "records_in_time_window": coverage.records_in_time_window,
            "nearby_records": coverage.nearby_records,
            "confidence": coverage.coverage_confidence,
            "reason": coverage.reason,
        },
    }


@app.post("/api/analyze-drift")
async def analyze_drift(request: DriftAnalysisRequest) -> Dict[str, Any]:
    try:
        return enrich_incident_with_drift(request.incident, request.observations, windage=request.windage, uncertainty_km=request.uncertainty_km)
    except (TypeError, ValueError) as exc:
        raise HTTPException(status_code=422, detail=f"Invalid drift input: {exc}") from exc


@app.post("/api/prepare-response")
async def prepare_response(request: PrepareResponseRequest) -> Dict[str, Any]:
    """Create a non-transmitting Coast Guard response draft."""
    response_id = f"IMW-RESPONSE-{uuid.uuid4().hex[:8].upper()}"
    return {
        "status": "DRAFT_REQUIRES_OPERATOR_CONFIRMATION",
        "response_id": response_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "recipient": request.recipient or "Indian Coast Guard — operator to confirm",
        "incident_id": request.incident_id,
        "urgency": "HIGH" if request.threat_score >= 0.8 else "REVIEW",
        "payload_preview": {
            "incident_id": request.incident_id,
            "slick_centroid": request.slick_centroid,
            "spill_area_sq_m": request.spill_area_sq_m,
            "candidate_vessel": request.suspect_vessel,
            "threat_score": request.threat_score,
            "evidence_summary": request.evidence_summary,
        },
        "operator_confirmation": {"required": True, "confirmed": False, "confirmed_by": None, "confirmed_at": None},
        "transmission": {"status": "NOT_SENT", "sent_at": None},
        "notice": "Draft only. Verify evidence and recipient details before any official transmission.",
    }


@app.post("/api/build-report")
async def build_report(request: BuildReportRequest) -> Dict[str, Any]:
    if not request.incident.get("incident_id"):
        raise HTTPException(status_code=422, detail="incident.incident_id is required")
    return build_incident_report(request.incident, request.response_draft)


@app.get("/")
async def root():
    return FileResponse(str(STATIC_DIR / "index.html"))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
